### ISSUE TITLE
Firmware and upstreaming

### ISSUE THREAD

**Issue by elboulangero** [RPi-Distro/bluez-firmware#7]
Dear RPI maintainers,

I see that this repository contains firmware that are needed to make the Raspberry Pi BT/WIFI work. I was wondering if there are any known attempt to push these firmware into https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git ? If not, is there any reason not to do so?

That would make it much easier for Linux distributions. Right now every distros that want to support the latest RPI ends up on this GitHub repo and wonders what's the best way to handle those wild firmware.

As a sidenote, I also noted that the upstream repo `bluez-firmware` is marked as deprecated, see http://www.bluez.org/download/.

The Debian package `bluez-firmware` (that was used as a base for this fork) didn't see any significant change since 2006: https://salsa.debian.org/bluetooth-team/bluez-firmware/-/commits/master . It seems to me that this repository was deprecated, and this fork brought it back from the dead :) But I might be wrong, I'm not very familiar with the bluez stack.

Cheers,

  Arnaud

**Comment by XECDesign** [comment]
Can't comment on upstreaming, but yes, it was initially added to bluez-firmware because that looked like the most appropriate place for it at the time. It should be moved to firmware-misc-nonfree at some point, but there's no reason to drop everything to do that right now.

**Comment by pelwell** [comment]
There are no plans for us to upstream Cypress's and Synaptic's firmwares.

**Comment by elboulangero** [comment]
Thanks for the quick reply.I close the issue then.
